#:schema node_modules/wrangler/config-schema.json
name = "cfblog-list-worker"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Bind a headless browser instance running on Cloudflare's global network.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#browser-rendering
[browser]
binding = "BROWSER"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = "cf-blog-list"
id = "your KV id"

[[kv_namespaces]]
binding = "cfblog-summary"
id = "your kv id"

[[queues.consumers]]
queue = 'cfblog-list-queue'
max_batch_size = 5
max_concurrency = 2
max_batch_timeout = 30

[[queues.producers]]
queue = "cfblog-list-queue"
binding = "queue"

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#workers-ai
[ai]
binding = "AI"

